const CONSTANTS = {
  COLOR_AXIS: '#DDD',
  COLOR_INSTANCE: '#99C',
  // COLOR_HOVERED: '#75D',
  COLOR_SELECTED: ['#195', '#D52'],
  OPACITY_INSTANCE_PCOORD: 0.25,
  OPACITY_INSTANCE_SCATTER: 0.75,
  OPACITY_SELECTED: 1,
  RADIUS_SCATTER: 6,
  STROKE_WIDTH_PCOORD: 3,
}